<?php
include("header.php");
?>
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <ul class="nav">
        <li<?php if ($page === null) { echo " class=\"active\""; } ?>><a href="./">Home</a></li>
        <li<?php if ($page === "profile") { echo " class=\"active\""; } ?>><a href="/profile">Profile</a></li>
        <li<?php if ($page === "about") { echo " class=\"active\""; } ?>><a href="/about">About</a></li>
        <li<?php if ($page === "contact") { echo " class=\"active\""; } ?>><a href="/contact">Contact</a></li>
      </ul>
    </div>
  </div>
</div>

<!-- Jumbotron -->
<div class="jumbotron">
  <div id="banner"></div>
  <h1>Get what you want, when you want it</h1>
  <h2>Connect with local businesses in real time</h2>
</div>


<div class="row-fluid">
  <div class="span12">
    <h2>Terms of Use Agreement</h2>
    <p>
      <p><strong>1.  READ BEFORE USE</strong></p>
      <p>This Terms of Use Agreement (“Agreement”) is made by and between Murray Hill Learning Group, Inc., DBA Fancy Chatter, Inc. (herein referred to as “Fancy Chatter”), an Indiana Corporation, and you (“user”).  This Agreement contains the terms and conditions that govern your use of this Web Site.</p>
      <p>BY CLICKING THE “I AGREE” BUTTON OR BY ACCESSING, VISTING, BROWSING, USING OR ATTEMPTING TO INTERACT WITH ANY PART OF THIS WEB SITE, OR OTHER FANCY CHATTER SOFTWARE, SERVICES, WEBSITES OR ANY OF FANCY CHATTER’S LICENSEES SERVICES OR SOFTWARE (COLLECTIVELY “SERVICES”), YOU AGREE THAT YOU HAVE READ, UNDERSTAND AND AGREE TO BE BOUND BY THIS AGREEMENT.  IF YOU DO NOT AGREE TO BE BOUND BY THIS AGREEMENT, DO NOT ACCESS OR USE ANY PART OF THIS WEBSITE.</p>
      <p>FANCY CHATTER RESERVES THE RIGHT, FROM TIME TO TIME, WITH OR WITHOUT NOTICE TO YOU, TO MAKE CHANGES TO THIS AGREEMENT IN FANCY CHATTER’S SOLE DISCRETION.  CONTINUED USE OF ANY PART OF THIS WEB SITE CONSITTUTES YOUR ACCEPTANCE OF SUCH CHANGES.  THE MOST CURRENT VERSION OF THIS AGREEMENT, WHICH SUPERCEDES ALL PREVIOUS VERSIONS, CAN BE REVIEWED BY CLICKING ON THE “TERMS OF USE” HYPERLINK LOCATED AT THE BOTTOM OF EVERY PAGE ON THE FANCY CHATTER WEBSITE.</p>
      <p><strong>2.  ACCESS TO THIS SITE</strong></p>
      <p>To access this site or some of the resources it offers, you may be asked to provide certain registration details or other information.  It is a condition of you use of this site that all the information you provide on this site will be correct, current, and complete.  If Fancy Chatter believes the information you provide is not correct, current, or complete, Fancy Chatter has the right to refuse your access to this site or any of its resources, and to terminate or suspend your access at any time.</p>
      <p><strong>3.  RESTRICTIONS ON USE</strong></p>
      <p>You may use this site for purposes expressly permitted by this site.  As a condition of your use of fancychatter.com, you warrant to Fancy Chatter that you will not use the website for any purpose that is unlawful or prohibited by these terms, conditions, and notices.  For example, you may not (and may not authorize any party to) (i) co-brand this site, or (ii) frame this site, without the express prior written permission of an authorized representative of Fancy Chatter.  For purposes of these Terms of Use, “co-branding” means to display a name, logo, trademark, or other means of attribution or identification of any party in such a manner as is reasonably likely to give a user the impression that such other party has the right to display, publish, or distribute this site or content accessible within this site.  You agree to cooperate with Fancy Chatter in causing any unauthorized co-branding, framing, or hyper linking immediately to cease.  In addition, you may not use fancychatter.com in any manner which could disable, overburden, damage or impair the website or interfere with any other party’s use and enjoyment of the website.  You may not obtain or attempt to obtain any materials, content, or information through any means not intentionally made available or provided for through the website.</p>
      <p><strong>4.  USE LIMITATION</strong></p>
      <p>Fancychatter.com is for your personal use in sending information to and receiving information from fancychatter.com members concerning their ordinary course of business.  You may not use this site for any other purpose, without Fancy Chatter’s express prior written consent.  Any unauthorized commercial use is prohibited.</p>
      <p><strong>5.  PROPRIETARY INFORMATION</strong></p>
      <p>The material and content accessible from this site (the “Content”) is the proprietary information of Fancy Chatter.  Accordingly, the Content may not be copied, distributed, republished, uploaded, posted, or transmitted in any way without the prior written consent of Fancy Chatter, except that you may print out a copy of the Content solely for your personal use.  In doing so, you may not remove or alter, or cause to be removed or altered, any copyright, trademark, trade name, service mark, or any other proprietary notice or legend appearing on any of the Content.  Modification or use of the Content except as expressly provided in the Terms of Use violates Fancy Chatter’s intellectual property rights.  Neither title nor intellectual property rights are transferred to you by access to this site.</p>
      <p><strong>6.  HYPER LINKS</strong></p>
      <p>This site may be hyper linked to other sites which are not maintained by, or related to, Fancy Chatter.  Hyper links to such sites are provided as a service to users and are not sponsored by or affiliated with this site or Fancy Chatter.  Fancy Chatter has not reviewed any or all of such sites and is not responsible for the content of those sites.  Fancy Chatter is not responsible for webcasting or any other form of transmission received from any hyper linked site.  Hyper links are to be accessed at the user’s own risk, and Fancy Chatter makes no representations or warranties about the content, completeness or accuracy of the hyper links or sites hyper linked to this site.  Fancy Chatter provides hyper links as a convenience, and the inclusion of any hyper link to a third party site does not necessarily imply endorsement by Fancy Chatter of that site or any association with its operators.</p>
      <p><strong>7.  USE OF COMMUNICATION SERVICES</strong></p>
      <p>Fancychatter.com may contain forums, bulletin board services, chat areas, message boards, news groups, communities, personal web pages, calendars, and/or other message or communication facilities designed to allow you to communicate with the Internet community or with a group (collectively, “Communication Services”).  You agree to use the Communication Services only to post, send and receive messages and content that are proper and related to the particular Communication Service.</p>
      <p>Among other actions, when using a Communication Service, you agree that you will not post, send, submit, publish, or transmit in connection with this site any material that:</p>
      <blockquote>
        i) you do not have the right to post, including proprietary material of any third party, such as files containing software or other material protected by intellectual property laws (or by rights or privacy or publicity);<br />
        ii) advocates illegal activity or discusses an intent to commit an illegal act;<br />
        iii) is vulgar, obscene, pornographic, or indecent;<br />
        iv) does not pertain directly to this site;<br />
        v) threatens or abuses others, libels, defames, invades privacy, stalks, is obscene, pornographic, racist, abusive, harassing, threatening or offensive;<br />`
        vi) seeks to exploit or harm children by exposing them to inappropriate content, asking for personally identifiable details or otherwise;</br>
        vii) harvests or otherwise collects information about others, including e-mail addresses, without their consent;<br />
        viii) violates any law or may be considered to violate any law;<br />
        ix) impersonates or misrepresents your connection to any other entity or person or otherwise manipulates header or identifiers to disguise the origin of the content;<br />
        x) falsifies or deletes any author attributions, legal or other proper notices or proprietary designations or labels of the origin or source of software or other material contained in a file that is permissible uploaded;<br />
        xi) includes programs that contain viruses, worms and/or Trojan horses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications;<br />
        xii) disrupts the normal flow of dialogue, causes a screen to scroll faster than other users are able to type, or otherwise act in a way which affects the ability of other people to engage in real time activities via this site;<br />
        xiii) amounts to a “pyramid” or other like scheme<br />
        xvii) disobeys any policy or regulations including any code of conduct or other guidelines, established from time to time regarding use of this site or any networks connected to this site; or<br />
        xviii) contains hyper-links to other sites that contain content that falls within the descriptions set forth above.<br />
      </blockquote>
      <p>Murray Hill reserves the right to monitor use of this site to determine compliance with these Terms of Use, as well as the right to remove or refuse any information for any reason. Murray Hill reserves the right to terminate your access to any or all of the Communication Services at any time without notice for any reason whatsoever. Murray Hill also reserves the right at all times to disclose any information as necessary to satisfy any applicable law, regulation, legal process or governmental request, or to edit, refuse to post or to remove any information or materials, in whole or in part, in its sole discretion.  Materials uploaded to a Communication Service may be subject to posted limits on use, reproduction and/or dissemination and you are responsible for abiding by such limitations with respect to your submissions, including any downloaded materials.</p>
      <p>Notwithstanding these rights, you remain solely responsible for the content of your submissions. You acknowledge and agree that neither Murray Hill nor any third party that provides Content to Murray Hill will assume or have any liability for any action or inaction by Murray Hill or such third party with respect to any submission. Murray Hill cautions you against giving out any personally identifying information about yourself or your children in any Communication Service. Murray Hill does not control or endorse the content, messages or information found in any Communication Service and, consequently, Murray Hill specifically disclaims any liability with respect to the Communication Services and any actions resulting from your participation in any Communication Service. Managers and hosts are not authorized Murray Hill spokespersons, and their views do not necessarily reflect those of Murray Hill.</p>
      <p><strong>8.  SUBMISSIONS</strong></p>
      <p>You hereby grant to Fancy Chatter the royalty-free, perpetual, irrevocable, worldwide, non-exclusive right and license to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform, and display all content, remarks, suggestions, ideas, graphics, or other information communicated through this site (together, the “Submission”), and to incorporate any Submission in other works in any form, media, or technology now known or later developed.  Fancy Chatter will not be required to treat any Submission as confidential, and may use any Submission in its business (including without limitation, for products or advertising) without incurring any liability for royalties or any other consideration of any kind, and will not incur any liability as a result of any similarities that may appear in future Fancy Chatter operations.</p>
      <p><strong>9.  DISCLAIMER</strong></p>
      <p>You understand that Fancy Chatter cannot and does not guarantee or warrant that files available for downloading from the Internet will be free of viruses, worms, Trojan Horses, or other code that may manifest contaminating or destructive properties.  You are responsible for implementing sufficient output, and for maintaining a means external to this site for any reconstruction of any lost data.  Fancy Chatter does not assume any responsibility or risk for your use of the Internet.</p>
      <p><strong>10.  LIMITATION ON LIABILITY</strong></p>
      <p>FANCY CHATTER, ITS SUBSIDIARIES, AFFILIATES, LICENSORS, SERVICE PROVIDERS, CONTENT PROVIDERS, EMPLOYEES, AGENTS, OFFICERS, AND DIRECTORS WILL NOT BE LIABLE FOR ANY INCIDENTAL, DIRECT, INDIRECT, PUNITITVE, ACTUAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, OR OTHER DAMAGES, INCLUDING LOSS OF REVENUE OR INCOME, PAIN AND SUFFERING, EMOTIONAL DISTRESS, OR SIMILAR DAMAGES, EVEN IF FANCY CHATTER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.  IN NO EVENT WILL THE COLLECTIVE LIABILITY OF FANCY CHATTER AND ITS SUBSIDIARIES, AFFILIATES, LICENSORS, SERVICE PROVIDERS, CONTENT PROVIDERS, EMPLOYEES, AGENTS, OFFICERS, AND DIRECTORS TO ANY PARTY (REGARDLESS OF THE FORM OF ACTION WHETHER IN CONTRACT, TORT, OR OTHERWISE) EXCEED THE GREATER OF $100 OR THE AMOUNT YOU HAVE PAID TO FANCY CHATTER FOR THE APPLICABLE CONTENT OR SERVICE OUT OF WHICH LIABILITY AROSE.</p>
      <p><strong>11.  TERMINATION OR RESTRICTION OF ACCESS</strong></p>
      <p>Fancy Chatter reserves the right, in its sole discretion, to terminate your access to any or all of Fancy Chatter’s websites and the related services or any portion thereof at any time, without notice.</p>
      <p><strong>12.  INDEMNITY</strong></p>
      <p>You will indemnify and hold Fancy Chatter, its subsidiaries, affiliates, licensors, content providers, service providers, employees, agents, officers, directors, and contractors (the “Indemnified Parties”) harmless from any breach of these Terms of Use by you, including any use of the Content other than as expressly authorized in these Terms of Use.  You agree that the Indemnified Parties will have no liability in connection with any such breach or unauthorized use, and you agree to indemnify any and all resulting loss, damages, judgments, awards, costs, expenses, and attorneys’ fees of the Indemnified Parties in connection therewith.  You will also indemnify and hold the Indemnified Parties harmless from and against any claims brought by third parties arising out of your use of the information accessed from this site.</p>
      <p><strong>13.  TRADEMARKS AND COPYRIGHTS</strong></p>
      <p>Trademarks, service marks, logos, and copyrighted works appearing in this site are the property of Fancy Chatter or the party that provided the trademarks, service marks, logos, and copyrighted works to Fancy Chatter.  Fancy Chatter and any party that provided trademarks, service marks, logos, and copyrighted works to Fancy Chatter retain all rights with respect to any of their respective trademarks, service marks, logos, and copyrighted works appearing in this site.</p>
      <p><strong>14.  SECURITY</strong></p>
      <p>Any passwords used for this site are for individual use only.  You will be responsible for the security of your password.  Fancy Chatter will be entitled to monitor your password and, at its discretion, require you to change it.  If you use a password that Fancy Chatter considers insecure, Fancy Chatter will be entitled to require the password to be changed and/or terminate you account.</p>
      <p>You are prohibited from using any services or facilities provided in connection with this site to compromise security or tamper with system resources and/or accounts.  The use or distribution of tools designed for compromising security (e.g., password guessing programs, cracking tools, or network probing tools) is strictly prohibited.  If you become involved in any violation of system security, Fancy Chatter reserves the right to release your details to system administrators at other sites in order to assist them in resolving security incidents.  Fancy Chatter reserves the right to investigate suspected violations of these Terms of Use.</p>
      <p>Fancy Chatter reserves the right to fully cooperate with any law enforcement authorities or court order requesting or directing Fancy Chatter to disclose the identity of anyone posting any e-mail messages, or publishing or otherwise making available any materials that are believed to violate these Terms of Use.  BY ACCEPTING THIS AGREEMENT YOU WAIVE AND HOLD HARMLESS MURRAY HILL FROM ANY CLAIMS RESULTING FROM ANY ACTION TAKEN BY FANCY CHATTER DURING OR AS A RESULT OF ITS INVESTIGATIONS AND/OR FROM ANY ACTIONS TAKEN AS A CONSEQUENCE OF INVESTIGATIONS BY EITHER FANCY CHATTER OR LAW ENFORCEMENT AUTHORITIES.</p>
      <p><strong>15.  MISCELLANEOUS</strong></p>
      <p>These Terms of Use will be governed and interpreted pursuant to the laws of Indiana, United States of America, notwithstanding any principles of conflicts of law.  You specifically consent to personal jurisdiction in Indiana in connection with any dispute between you and Fancy Chatter arising out of these Terms of Use or pertaining to the subject matter hereof.  The parties to these Terms of Use each agree that the exclusive venue for any dispute between the parties arising out of these Terms of Use will be in the state and federal courts in Indiana.</p>
      <p>A printed version of this agreement and any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form.</p>
      <p>Notwithstanding the foregoing, any additional terms and conditions on this site will govern the items to which they pertain.</p>
      <p>Fancy Chatter may revise these Terms of Use at any time by updating this posting.</p>
    </p>
  </div>
</div>
<?php
include("footer.php");
?>
